version: '3'
services:
    dd-test-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dd-test-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: dd-test-app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - dd-test-network

    dd-test-nginx:
        image: nginx:alpine
        container_name: dd-test-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/dev/:/etc/nginx/conf.d/
        networks:
            - dd-test-network

    dd-test-db:
        image: mysql:8.0.20
        container_name: dd-test-db
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: wMnck4aG3DJv6JoUYN3y
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql2
        networks:
            - dd-test-network

networks:
    dd-test-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
